"""update sections for transcription processing

Revision ID: 3017cbd0e8ca
Revises: b3f8e2a1d4c5
Create Date: 2026-02-14 17:29:44.172032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3017cbd0e8ca'
down_revision = 'b3f8e2a1d4c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('idx_books_status', table_name='books')
    op.add_column('sections', sa.Column('source_transcription_id', sa.UUID(), nullable=True))
    op.add_column('sections', sa.Column('source_slide_id', sa.UUID(), nullable=True))
    op.alter_column('sections', 'video_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('idx_sections_status', table_name='sections')
    op.create_foreign_key(None, 'sections', 'transcriptions', ['source_transcription_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'sections', 'slides', ['source_slide_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.create_index('idx_sections_status', 'sections', ['status'], unique=False)
    op.alter_column('sections', 'video_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('sections', 'source_slide_id')
    op.drop_column('sections', 'source_transcription_id')
    op.create_index('idx_books_status', 'books', ['status'], unique=False)
    op.drop_table('transcriptions')
    op.drop_table('slides')
    # ### end Alembic commands ###
