"""add_bibliography_and_slide_page

Revision ID: ff34493e6a47
Revises: 3017cbd0e8ca
Create Date: 2026-02-14 18:32:51.655905

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ff34493e6a47'
down_revision = '3017cbd0e8ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section_assets', sa.Column('slide_page', sa.Integer(), nullable=True))
    op.add_column('sections', sa.Column('bibliography', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sections', 'bibliography')
    op.drop_column('section_assets', 'slide_page')
    # ### end Alembic commands ###
